openapi: 3.0.0
info:
  title: Chitter API
  version: "1.0"
  description: API for Chitter chat application

servers:
  - url: http://localhost:3000
    description: Development server
  - url: https://api.chitter.com
    description: Production server

security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /v1/signin:
    post:
      tags: [auth]
      security: [] # Override root security - no auth needed
      summary: Sign in user
      responses:
        "200":
          description: Successful sign in
        "401":
          description: Unauthorized

  /v1/me:
    get:
      tags: [user]
      security:
        - BearerAuth: []
      summary: Get current user info
      responses:
        "200":
          description: User info retrieved

  /v1/me/friends:
    get:
      tags: [friends]
      security:
        - BearerAuth: []
      summary: Get user's friends list
      responses:
        "200":
          description: Friends list retrieved

  /v1/me/friend/requests/received:
    get:
      tags: [friends]
      security:
        - BearerAuth: []
      summary: Get received friend requests
      responses:
        "200":
          description: Friend requests retrieved

  /v1/me/friend/request:
    post:
      tags: [friends]
      security:
        - BearerAuth: []
      summary: Send a friend request
      responses:
        "200":
          description: Friend request sent

  /v1/me/friend/add:
    post:
      tags: [friends]
      security:
        - BearerAuth: []
      summary: Accept a friend request
      responses:
        "200":
          description: Friend request accepted

  /v1/user:
    get:
      tags: [user]
      security: [] # Override root security - no auth needed
      summary: Search for users
      parameters:
        - name: query
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Users found

  /v1/me/groups:
    get:
      tags: [rooms]
      security:
        - BearerAuth: []
      summary: Get user's groups
      responses:
        "200":
          description: Groups retrieved

  /v1/room/oneone:
    post:
      tags: [rooms]
      security:
        - BearerAuth: []
      summary: Join or create 1:1 chat room
      responses:
        "200":
          description: Room joined/created

  /v1/room/groups:
    get:
      tags: [rooms]
      security:
        - BearerAuth: []
      summary: Search for groups
      responses:
        "200":
          description: Groups found

  /v1/room/groups/{id}:
    get:
      tags: [rooms]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      summary: Get group details
      responses:
        "200":
          description: Group details retrieved

  /v1/room/group/join:
    post:
      tags: [rooms]
      security:
        - BearerAuth: []
      summary: Join a group
      responses:
        "200":
          description: Joined group

  /v1/room/group/create:
    post:
      tags: [rooms]
      security:
        - BearerAuth: []
      summary: Create a new group
      responses:
        "200":
          description: Group created

  /v1/room/msg:
    post:
      tags: [rooms]
      security:
        - BearerAuth: []
      summary: Get room messages
      responses:
        "200":
          description: Messages retrieved

  /v1/theme:
    post:
      tags: [themes]
      security:
        - BearerAuth: []
      summary: Create new theme
      responses:
        "200":
          description: Theme created

  /v1/themes/{id}:
    delete:
      tags: [themes]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      summary: Delete a theme
      responses:
        "200":
          description: Theme deleted

  /v1/me/themes:
    get:
      tags: [themes]
      security:
        - BearerAuth: []
      summary: Get user's themes
      responses:
        "200":
          description: Themes retrieved

  /v1/themes/{id}/publish:
    post:
      tags: [marketplace]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      summary: Publish theme to marketplace
      responses:
        "200":
          description: Theme published

  /v1/themes/{id}/apply:
    post:
      tags: [themes]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      summary: Apply theme to user's chat
      responses:
        "200":
          description: Theme applied

  /v1/market:
    get:
      tags: [marketplace]
      security:
        - BearerAuth: []
      summary: Get marketplace themes
      responses:
        "200":
          description: Marketplace themes retrieved

  /v1/themes/{id}/download:
    post:
      tags: [marketplace]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      summary: Download theme to user's collection
      responses:
        "200":
          description: Theme downloaded
