version: "3.8"

services:
  express:
    image: chitter/express-server:1.0
    ports:
      - "8000:8000"
    restart: unless-stopped

  zookeeper:
    hostname: zookeeper
    image: bitnami/zookeeper:latest
    restart: always
    expose:
      - "2181"
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    hostname: kafka
    image: bitnami/kafka:2.7.0
    restart: always
    env_file:
      - Dockerbuild/kafka.env
    depends_on:
      - zookeeper
    expose:
      - "9092"
    ports:
      - "9092:9092"

  runkafka:
    image: apache/kafka:3.7.0
    volumes:
      - ./Dockerbuild/kafka/:/app/kafka
    depends_on:
      - kafka
    command: sh -c "sleep 5 && cd /app/kafka && ls && ./runkafka.sh"

  gopqms:
    image: chitter/go-ms:1.0
    depends_on:
      - kafka
    environment:
      KAFKA_URL: kafka:9092
    restart: unless-stopped
