scrape_configs:
  - job_name: "k6"
    static_configs:
      - targets: ["k6:6565"] # k6's embedded Prometheus server

  - job_name: "mongodb"
    static_configs:
      - targets: ["mongo:9216"] # MongoDB Exporter port
