version: "3.8"

services:
  express:
    image: chitter/express:1.0
    environment:
      - KAFKA_URL=host.docker.internal:9092
    ports:
      - "8000:8000"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  go:
    image: chitter/gomsq:1.0
    environment:
      - KAFKA_URL=host.docker.internal:9092

    extra_hosts:
      - "host.docker.internal:host-gateway"
