version: "3.8"

name: main-server
services:
  mongodb:
    env_file: .env
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

  express:
    env_file: .env
    image: chitter/express:1.0
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    depends_on:
      startup_broker:
        condition: service_completed_successfully
      broker:
        condition: service_healthy

  startup_broker:
    env_file: .env
    image: apache/kafka:latest
    depends_on:
      broker:
        condition: service_healthy
    command: >
      bash -c 
      ' 
      cd ./opt/kafka/bin;
      ./kafka-topics.sh --create --bootstrap-server broker:9092 --topic msg-persist; 
      ./kafka-topics.sh --create --bootstrap-server broker:9092 --topic msg-persist-done; 
      echo "Startup broker completed successfully";
      '

    restart: "no" # important: don't retry

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-topics --bootstrap-server broker:9092 --list || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  # broker:
  #   env_file: .env
  #   image: apache/kafka:latest
  #   container_name: broker
  #   ports:
  #     - 9092:9092
  #     - 9093:9093
  #     - 9094:9094
  #   healthcheck:
  #     test:
  #       [
  #         "CMD-SHELL",
  #         "./opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server broker:9092 > /dev/null 2>&1",
  #       ]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 5

  go:
    env_file: .env
    image: chitter/gomsq:1.0
    depends_on:
      startup_broker:
        condition: service_completed_successfully
      broker:
        condition: service_healthy
