run: 
	docker run --name mongodb -p 27017:27017 -d mongodb/mongodb-community-server:latest

connect:
	mongosh --port 27017

run_db_test:  
	docker run --name mongodb-test -p 27017:27017 -d mongodb/mongodb-community-server:latest 




# db.runCommand(
#    {
#       hello: 1
#    }
# )
